services:
  postgres:
    image: postgres:18-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: autoparts
    ports:
      - "5435:5432"
    volumes:
      - pgdata:/var/lib/postgresql

  redis:
    image: redis:7.4-alpine
    ports:
      - "6382:6379"

  backend:
    build: ./backend
    ports:
      - "8080:8000"
    environment:
      POSTGRES_SERVER: postgres
      POSTGRES_PORT: 5432
      REDIS_HOST: redis
      REDIS_PORT: 6379
    volumes:
      - ./backend:/app
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - postgres
      - redis
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

  celery_worker:
    build: ./backend
    container_name: celery_worker
    command: celery -A app.workers worker --loglevel=info
    environment:
      POSTGRES_SERVER: postgres
      POSTGRES_PORT: 5432
      REDIS_HOST: redis
      REDIS_PORT: 6379
      TZ: Europe/Kyiv
    depends_on:
      - redis
      - postgres
    restart: unless-stopped

  celery_beat:
    build: ./backend
    command: celery -A app.workers beat --loglevel=info
    environment:
      POSTGRES_SERVER: postgres
      POSTGRES_PORT: 5432
      REDIS_HOST: redis
      REDIS_PORT: 6379
      TZ: Europe/Kyiv
    depends_on:
      - redis
      - postgres
    restart: unless-stopped

  frontend:
    build: ./frontend
    ports:
      - "3080:3000"
    depends_on:
      - backend
    environment:
      - INTERNAL_API_URL=http://backend:8000/api/v1

volumes:
  pgdata:
