"""add unique constraint on supplier_prices supplier article

Revision ID: 0effb110f9a6
Revises: 5b1fc88bb68d
Create Date: 2026-06-26 15:04:18.191224

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0effb110f9a6'
down_revision: Union[str, Sequence[str], None] = '5b1fc88bb68d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_supplier_prices_supplier_article', table_name='supplier_prices')
    op.create_unique_constraint('uq_supplier_prices_supplier_article', 'supplier_prices', ['supplier', 'article'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_supplier_prices_supplier_article', 'supplier_prices', type_='unique')
    op.create_index('ix_supplier_prices_supplier_article', 'supplier_prices', ['supplier', 'article'], unique=True)
    # ### end Alembic commands ###
