"""update_novapay_settings

Revision ID: 1bbd03898fff
Revises: d22ebf87bd60
Create Date: 2026-07-02 17:27:50.616570

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1bbd03898fff'
down_revision: Union[str, Sequence[str], None] = 'd22ebf87bd60'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('site_settings', sa.Column('novapay_merchant_id', sa.String(), nullable=True))
    op.add_column('site_settings', sa.Column('novapay_private_key_encrypted', sa.Text(), nullable=True))
    op.drop_column('site_settings', 'novapay_api_key_encrypted')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('site_settings', sa.Column('novapay_api_key_encrypted', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_column('site_settings', 'novapay_private_key_encrypted')
    op.drop_column('site_settings', 'novapay_merchant_id')
    # ### end Alembic commands ###
