"""add backup_records table and backup_run_at_time to site_settings

Revision ID: 2db168de1889
Revises: e8593c313731
Create Date: 2026-07-13 17:46:25.266009

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2db168de1889'
down_revision: Union[str, Sequence[str], None] = 'e8593c313731'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('backup_records',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('filename', sa.String(), nullable=False),
    sa.Column('filepath', sa.Text(), nullable=False),
    sa.Column('file_size', sa.BigInteger(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('site_settings', sa.Column('backup_run_at_time', sa.String(), nullable=True))
    op.execute("UPDATE site_settings SET backup_run_at_time = '02:00' WHERE backup_run_at_time IS NULL")
    op.alter_column('site_settings', 'backup_run_at_time', nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('site_settings', 'backup_run_at_time')
    op.drop_table('backup_records')
    # ### end Alembic commands ###
