"""add return recipient fields

Revision ID: 3824bee769f5
Revises: 56607398eae3
Create Date: 2026-06-25 15:47:07.647973

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3824bee769f5'
down_revision: Union[str, Sequence[str], None] = '56607398eae3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('return_requests', sa.Column('return_phone', sa.String(length=32), nullable=True))
    op.add_column('return_requests', sa.Column('return_last_name', sa.String(length=100), nullable=True))
    op.add_column('return_requests', sa.Column('return_first_name', sa.String(length=100), nullable=True))
    op.add_column('return_requests', sa.Column('return_middle_name', sa.String(length=100), nullable=True))
    op.add_column('return_requests', sa.Column('return_delivery_city', sa.String(length=255), nullable=True))
    op.add_column('return_requests', sa.Column('return_delivery_warehouse', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('return_requests', 'return_delivery_warehouse')
    op.drop_column('return_requests', 'return_delivery_city')
    op.drop_column('return_requests', 'return_middle_name')
    op.drop_column('return_requests', 'return_first_name')
    op.drop_column('return_requests', 'return_last_name')
    op.drop_column('return_requests', 'return_phone')
    # ### end Alembic commands ###
