"""add google oauth columns to site_settings

Revision ID: 5b1fc88bb68d
Revises: 936173f53599
Create Date: 2026-06-26 13:00:21.228317

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5b1fc88bb68d'
down_revision: Union[str, Sequence[str], None] = '936173f53599'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('site_settings', sa.Column('google_client_id', sa.String(), nullable=True))
    op.add_column('site_settings', sa.Column('google_client_secret_encrypted', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('site_settings', 'google_client_secret_encrypted')
    op.drop_column('site_settings', 'google_client_id')
    # ### end Alembic commands ###
