"""add is_active to parts

Revision ID: 73fd9a3560b7
Revises: ba1b3042aa9e
Create Date: 2026-06-25 18:58:21.379116

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '73fd9a3560b7'
down_revision: Union[str, Sequence[str], None] = 'ba1b3042aa9e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('parts', sa.Column('is_active', sa.Boolean(), nullable=True))
    op.add_column('parts', sa.Column('deactivated_at', sa.DateTime(), nullable=True))
    op.add_column('parts', sa.Column('deactivation_reason', sa.String(), nullable=True))
    op.create_index(op.f('ix_parts_is_active'), 'parts', ['is_active'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_parts_is_active'), table_name='parts')
    op.drop_column('parts', 'deactivation_reason')
    op.drop_column('parts', 'deactivated_at')
    op.drop_column('parts', 'is_active')
    # ### end Alembic commands ###
