"""add ticket_number, remove subject from chats

Revision ID: 87273b541958
Revises: 0e9dceb9f758
Create Date: 2026-07-06 16:55:12.945969

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '87273b541958'
down_revision: Union[str, Sequence[str], None] = '0e9dceb9f758'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat_conversations', sa.Column('ticket_number', sa.String(length=20), nullable=True))
    op.create_index(op.f('ix_chat_conversations_ticket_number'), 'chat_conversations', ['ticket_number'], unique=True)
    # Backfill ticket_number for existing chats
    op.execute("UPDATE chat_conversations SET ticket_number = 'TKT-' || LPAD(id::text, 10, '0') WHERE ticket_number IS NULL")
    op.alter_column('chat_conversations', 'ticket_number', nullable=False)
    op.drop_column('chat_conversations', 'subject')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat_conversations', sa.Column('subject', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_chat_conversations_ticket_number'), table_name='chat_conversations')
    op.drop_column('chat_conversations', 'ticket_number')
    # ### end Alembic commands ###
