"""add email settings columns to site_settings

Revision ID: 936173f53599
Revises: e4abf7d63e1b
Create Date: 2026-06-26 12:11:09.945690

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '936173f53599'
down_revision: Union[str, Sequence[str], None] = 'e4abf7d63e1b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('site_settings', sa.Column('resend_api_key_encrypted', sa.Text(), nullable=True))
    op.add_column('site_settings', sa.Column('email_from', sa.String(), nullable=False, server_default='noreply@svom.com.ua'))
    op.add_column('site_settings', sa.Column('email_from_name', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('site_settings', 'email_from_name')
    op.drop_column('site_settings', 'email_from')
    op.drop_column('site_settings', 'resend_api_key_encrypted')
    # ### end Alembic commands ###
