"""add supplier_article to parts

Revision ID: 9498e8297b2e
Revises: 11bdf36d2f09
Create Date: 2026-06-26 19:41:49.376617

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9498e8297b2e'
down_revision: Union[str, Sequence[str], None] = '11bdf36d2f09'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('parts', sa.Column('supplier_article', sa.String(), nullable=True))
    op.create_index('idx_part_supplier_article_brand', 'parts', ['supplier_article', 'brand'], unique=False)
    op.create_index(op.f('ix_parts_supplier_article'), 'parts', ['supplier_article'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_parts_supplier_article'), table_name='parts')
    op.drop_index('idx_part_supplier_article_brand', table_name='parts')
    op.drop_column('parts', 'supplier_article')
    # ### end Alembic commands ###
