"""add_telegram_settings

Revision ID: 99562a6fc3bd
Revises: a2b3c4d5e6f7
Create Date: 2026-07-11 11:01:05.997524

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '99562a6fc3bd'
down_revision: Union[str, Sequence[str], None] = 'a2b3c4d5e6f7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('chat_conversations', 'ticket_number',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    op.add_column('site_settings', sa.Column('telegram_bot_token_encrypted', sa.Text(), nullable=True))
    op.add_column('site_settings', sa.Column('telegram_chat_id', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('site_settings', 'telegram_chat_id')
    op.drop_column('site_settings', 'telegram_bot_token_encrypted')
    op.alter_column('chat_conversations', 'ticket_number',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    # ### end Alembic commands ###
