"""add_payment_integration

Revision ID: 99da8db74a4a
Revises: c1ac934f5c3f
Create Date: 2026-07-02 15:50:00.948551

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '99da8db74a4a'
down_revision: Union[str, Sequence[str], None] = 'c1ac934f5c3f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('payment_transactions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('payment_method', sa.String(length=32), nullable=False, comment='cod | monobank | novapay | liqpay'),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False, comment='pending | paid | failed | refunded | expired'),
    sa.Column('provider_tx_id', sa.String(length=255), nullable=True, comment='ID транзакции в банке'),
    sa.Column('payment_url', sa.Text(), nullable=True, comment='Ссылка на оплату'),
    sa.Column('invoice_url', sa.Text(), nullable=True, comment='Ссылка на инвойс'),
    sa.Column('receipt_url', sa.Text(), nullable=True, comment='Ссылка на квитанцию'),
    sa.Column('meta', sa.JSON(), nullable=True, comment='Банк-специфичные данные'),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payment_transactions_order_id'), 'payment_transactions', ['order_id'], unique=False)
    op.add_column('site_settings', sa.Column('payment_cod_enabled', sa.Boolean(), server_default=sa.text('true'), nullable=False))
    op.add_column('site_settings', sa.Column('payment_monobank_enabled', sa.Boolean(), server_default=sa.text('true'), nullable=False))
    op.add_column('site_settings', sa.Column('payment_novapay_enabled', sa.Boolean(), server_default=sa.text('true'), nullable=False))
    op.add_column('site_settings', sa.Column('payment_liqpay_enabled', sa.Boolean(), server_default=sa.text('true'), nullable=False))
    op.add_column('site_settings', sa.Column('fondy_merchant_id', sa.String(), nullable=True))
    op.add_column('site_settings', sa.Column('fondy_secret_key_encrypted', sa.Text(), nullable=True))
    op.add_column('site_settings', sa.Column('liqpay_public_key_encrypted', sa.Text(), nullable=True))
    op.add_column('site_settings', sa.Column('liqpay_private_key_encrypted', sa.Text(), nullable=True))
    op.add_column('site_settings', sa.Column('novapay_api_key_encrypted', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('site_settings', 'novapay_api_key_encrypted')
    op.drop_column('site_settings', 'liqpay_private_key_encrypted')
    op.drop_column('site_settings', 'liqpay_public_key_encrypted')
    op.drop_column('site_settings', 'fondy_secret_key_encrypted')
    op.drop_column('site_settings', 'fondy_merchant_id')
    op.drop_column('site_settings', 'payment_liqpay_enabled')
    op.drop_column('site_settings', 'payment_novapay_enabled')
    op.drop_column('site_settings', 'payment_monobank_enabled')
    op.drop_column('site_settings', 'payment_cod_enabled')
    op.drop_index(op.f('ix_payment_transactions_order_id'), table_name='payment_transactions')
    op.drop_table('payment_transactions')
    # ### end Alembic commands ###
