"""add_protection_tables

Revision ID: a2b3c4d5e6f7
Revises: 87273b541958
Create Date: 2026-07-07 18:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a2b3c4d5e6f7'
down_revision: Union[str, Sequence[str], None] = '87273b541958'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Create protection tables."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ban_records',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('user_id', sa.Integer(), sa.ForeignKey('users.id'), nullable=True, index=True),
        sa.Column('email', sa.String(), nullable=True),
        sa.Column('ip_address', sa.String(), nullable=True),
        sa.Column('reason', sa.Text(), nullable=False),
        sa.Column('banned_by_id', sa.Integer(), sa.ForeignKey('users.id'), nullable=True),
        sa.Column('banned_at', sa.DateTime(), nullable=True),
        sa.Column('unbanned_at', sa.DateTime(), nullable=True),
        sa.Column('is_active', sa.Boolean(), default=True, index=True),
        sa.Column('block_count', sa.Integer(), default=1),
        sa.Column('ban_type', sa.String(), default='manual'),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_index('idx_ban_email_active', 'ban_records', ['email', 'is_active'])
    op.create_index('idx_ban_user_active', 'ban_records', ['user_id', 'is_active'])

    op.create_table('protection_events',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('user_id', sa.Integer(), sa.ForeignKey('users.id'), nullable=True, index=True),
        sa.Column('email', sa.String(), nullable=True),
        sa.Column('ip_address', sa.String(), nullable=True),
        sa.Column('event_type', sa.String(), nullable=False, index=True),
        sa.Column('description', sa.Text(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True, index=True),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_index('idx_event_user', 'protection_events', ['user_id', 'event_type'])
    op.create_index('idx_event_created', 'protection_events', ['created_at'])

    op.create_table('whitelist',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('user_id', sa.Integer(), sa.ForeignKey('users.id'), nullable=True, index=True),
        sa.Column('email', sa.String(), nullable=True, unique=True),
        sa.Column('ip_address', sa.String(), nullable=True, unique=True),
        sa.Column('reason', sa.Text(), nullable=True),
        sa.Column('added_by_id', sa.Integer(), sa.ForeignKey('users.id'), nullable=True),
        sa.Column('added_at', sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint('id'),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Drop protection tables."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('whitelist')
    op.drop_table('protection_events')
    op.drop_table('ban_records')
    # ### end Alembic commands ###
