"""add ttn_number to return_requests

Revision ID: ba1b3042aa9e
Revises: 3824bee769f5
Create Date: 2026-06-25 17:30:29.395286

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ba1b3042aa9e'
down_revision: Union[str, Sequence[str], None] = '3824bee769f5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('return_requests', sa.Column('ttn_number', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('return_requests', 'ttn_number')
    # ### end Alembic commands ###
