"""add_checkbox_integration

Revision ID: c1ac934f5c3f
Revises: d4e5f6a7b8c9
Create Date: 2026-07-02 14:50:51.714054

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c1ac934f5c3f'
down_revision: Union[str, Sequence[str], None] = 'd4e5f6a7b8c9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('order_checkbox_receipts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('receipt_id', sa.String(length=100), nullable=True, comment='ID чека в Checkbox'),
    sa.Column('status', sa.String(length=20), nullable=False, comment='pending | created | error'),
    sa.Column('fiscal_code', sa.String(length=100), nullable=True, comment='Фіскальний номер'),
    sa.Column('fiscal_date', sa.DateTime(), nullable=True),
    sa.Column('receipt_url', sa.Text(), nullable=True, comment='Посилання на чек'),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_order_checkbox_receipts_order_id'), 'order_checkbox_receipts', ['order_id'], unique=False)
    op.drop_index('uq_parts_article_brand', table_name='parts')
    op.create_index(op.f('ix_promocodes_user_id'), 'promocodes', ['user_id'], unique=False)
    op.add_column('site_settings', sa.Column('checkbox_api_key_encrypted', sa.Text(), nullable=True))
    op.add_column('site_settings', sa.Column('checkbox_organization_id', sa.String(), nullable=True))
    op.add_column('site_settings', sa.Column('checkbox_is_test', sa.Boolean(), nullable=False, server_default=sa.text('true')))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('site_settings', 'checkbox_is_test')
    op.drop_column('site_settings', 'checkbox_organization_id')
    op.drop_column('site_settings', 'checkbox_api_key_encrypted')
    op.drop_index(op.f('ix_promocodes_user_id'), table_name='promocodes')
    op.create_index('uq_parts_article_brand', 'parts', ['article', sa.text("COALESCE(brand, ''::character varying)")], unique=True)
    op.drop_index(op.f('ix_order_checkbox_receipts_order_id'), table_name='order_checkbox_receipts')
    op.drop_table('order_checkbox_receipts')
    # ### end Alembic commands ###
