"""add updated_by to return_requests

Revision ID: c767e944ee9e
Revises: e4f7a3b9c2d1
Create Date: 2026-06-25 13:25:32.214128

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c767e944ee9e'
down_revision: Union[str, Sequence[str], None] = 'e4f7a3b9c2d1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('footer_content', 'data',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=False,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.create_index(op.f('ix_order_items_order_id'), 'order_items', ['order_id'], unique=False)
    op.create_index(op.f('ix_order_nova_poshta_waybill_seats_waybill_id'), 'order_nova_poshta_waybill_seats', ['waybill_id'], unique=False)
    op.create_index(op.f('ix_orders_status'), 'orders', ['status'], unique=False)
    op.create_index(op.f('ix_orders_user_id'), 'orders', ['user_id'], unique=False)
    op.drop_index('ix_parts_article_brand', table_name='parts')
    op.drop_constraint('uq_parts_article_brand', 'parts', type_='unique')
    op.create_index(op.f('ix_parts_article'), 'parts', ['article'], unique=False)
    op.create_index(op.f('ix_price_rule_history_price_rule_id'), 'price_rule_history', ['price_rule_id'], unique=False)
    op.alter_column('price_rules', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
    op.create_index(op.f('ix_price_rules_category_id'), 'price_rules', ['category_id'], unique=False)
    op.add_column('return_requests', sa.Column('updated_by_user_id', sa.Integer(), nullable=True))
    op.add_column('return_requests', sa.Column('updated_by_name', sa.String(), nullable=True))
    op.add_column('return_requests', sa.Column('updated_by_group', sa.String(), nullable=True))
    op.create_foreign_key(None, 'return_requests', 'users', ['updated_by_user_id'], ['id'])
    op.alter_column('roles', 'is_system',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.drop_index('ix_supplier_offers_final_price', table_name='supplier_offers')
    op.drop_index('ix_supplier_prices_article', table_name='supplier_prices')
    op.drop_index('ix_supplier_prices_match_status', table_name='supplier_prices')
    op.drop_index('ix_supplier_prices_supplier', table_name='supplier_prices')
    op.drop_index('uq_supplier_prices_article_supplier', table_name='supplier_prices')
    op.drop_constraint('uq_supplier_prices_supplier_article', 'supplier_prices', type_='unique')
    op.drop_index('ix_tecdoc_rate_logs_called_at', table_name='tecdoc_rate_logs')
    op.create_index(op.f('ix_users_role_id'), 'users', ['role_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_role_id'), table_name='users')
    op.create_index('ix_tecdoc_rate_logs_called_at', 'tecdoc_rate_logs', ['called_at'], unique=False)
    op.create_unique_constraint('uq_supplier_prices_supplier_article', 'supplier_prices', ['supplier', 'article'], postgresql_nulls_not_distinct=False)
    op.create_index('uq_supplier_prices_article_supplier', 'supplier_prices', ['article', 'brand', 'supplier'], unique=True)
    op.create_index('ix_supplier_prices_supplier', 'supplier_prices', ['supplier'], unique=False)
    op.create_index('ix_supplier_prices_match_status', 'supplier_prices', ['match_status'], unique=False)
    op.create_index('ix_supplier_prices_article', 'supplier_prices', ['article'], unique=False)
    op.create_index('ix_supplier_offers_final_price', 'supplier_offers', ['final_price'], unique=False)
    op.alter_column('roles', 'is_system',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.drop_constraint(None, 'return_requests', type_='foreignkey')
    op.drop_column('return_requests', 'updated_by_group')
    op.drop_column('return_requests', 'updated_by_name')
    op.drop_column('return_requests', 'updated_by_user_id')
    op.drop_index(op.f('ix_price_rules_category_id'), table_name='price_rules')
    op.alter_column('price_rules', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))
    op.drop_index(op.f('ix_price_rule_history_price_rule_id'), table_name='price_rule_history')
    op.drop_index(op.f('ix_parts_article'), table_name='parts')
    op.create_unique_constraint('uq_parts_article_brand', 'parts', ['article', 'brand'], postgresql_nulls_not_distinct=False)
    op.create_index('ix_parts_article_brand', 'parts', ['article', sa.text("COALESCE(brand, ''::character varying)")], unique=True)
    op.drop_index(op.f('ix_orders_user_id'), table_name='orders')
    op.drop_index(op.f('ix_orders_status'), table_name='orders')
    op.drop_index(op.f('ix_order_nova_poshta_waybill_seats_waybill_id'), table_name='order_nova_poshta_waybill_seats')
    op.drop_index(op.f('ix_order_items_order_id'), table_name='order_items')
    op.alter_column('footer_content', 'data',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=False,
               existing_server_default=sa.text("'{}'::jsonb"))
    # ### end Alembic commands ###
