"""replace_fondy_with_monobank

Revision ID: d22ebf87bd60
Revises: 99da8db74a4a
Create Date: 2026-07-02 16:20:19.842525

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd22ebf87bd60'
down_revision: Union[str, Sequence[str], None] = '99da8db74a4a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('site_settings', sa.Column('monobank_token_encrypted', sa.Text(), nullable=True))
    op.drop_column('site_settings', 'fondy_secret_key_encrypted')
    op.drop_column('site_settings', 'fondy_merchant_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('site_settings', sa.Column('fondy_merchant_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('site_settings', sa.Column('fondy_secret_key_encrypted', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_column('site_settings', 'monobank_token_encrypted')
    # ### end Alembic commands ###
