"""add recipient counterparty type and label to waybills

Revision ID: ded47f050b9a
Revises: e40ec7429134
Create Date: 2026-07-24 15:28:10.229618

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ded47f050b9a'
down_revision: Union[str, Sequence[str], None] = 'e40ec7429134'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order_nova_poshta_waybills', sa.Column('recipient_counterparty_type', sa.String(length=32), nullable=True))
    op.add_column('order_nova_poshta_waybills', sa.Column('recipient_counterparty_label', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('order_nova_poshta_waybills', 'recipient_counterparty_label')
    op.drop_column('order_nova_poshta_waybills', 'recipient_counterparty_type')
    # ### end Alembic commands ###
