"""add supplier_offer_id to order_items

Revision ID: e109c4664354
Revises: 99562a6fc3bd
Create Date: 2026-07-13 14:53:44.913717

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e109c4664354'
down_revision: Union[str, Sequence[str], None] = '99562a6fc3bd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order_items', sa.Column('supplier_offer_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_order_items_supplier_offer_id'), 'order_items', ['supplier_offer_id'], unique=False)
    op.create_foreign_key(None, 'order_items', 'supplier_offers', ['supplier_offer_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'order_items', type_='foreignkey')
    op.drop_index(op.f('ix_order_items_supplier_offer_id'), table_name='order_items')
    op.drop_column('order_items', 'supplier_offer_id')
    # ### end Alembic commands ###
