"""add image_url to parts

Revision ID: e4abf7d63e1b
Revises: 73fd9a3560b7
Create Date: 2026-06-25 19:25:57.176055

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e4abf7d63e1b'
down_revision: Union[str, Sequence[str], None] = '73fd9a3560b7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('parts', sa.Column('image_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('parts', 'image_url')
    # ### end Alembic commands ###
