"""add_monopay_settings

Revision ID: f54307c2b051
Revises: 1bbd03898fff
Create Date: 2026-07-02 17:59:24.795488

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f54307c2b051'
down_revision: Union[str, Sequence[str], None] = '1bbd03898fff'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('site_settings', sa.Column('monobank_monopay_key_id', sa.String(), nullable=True))
    op.add_column('site_settings', sa.Column('monobank_ecdsa_private_key_encrypted', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('site_settings', 'monobank_ecdsa_private_key_encrypted')
    op.drop_column('site_settings', 'monobank_monopay_key_id')
    # ### end Alembic commands ###
