"""add bank_card to return_requests

Revision ID: f95c1399731f
Revises: ded47f050b9a
Create Date: 2026-07-24 17:20:34.256109

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f95c1399731f'
down_revision: Union[str, Sequence[str], None] = 'ded47f050b9a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('return_requests', sa.Column('bank_card', sa.String(length=19), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('return_requests', 'bank_card')
    # ### end Alembic commands ###
