# Price defaults
PRICE_PRECISION = 10
PRICE_SCALE = 2
DEFAULT_CURRENCY = "RUB"

# Pagination defaults
SEARCH_DEFAULT_LIMIT = 20
SEARCH_MIN_LIMIT = 1
SEARCH_MAX_LIMIT = 100

AUTOCOMPLETE_DEFAULT_LIMIT = 5
AUTOCOMPLETE_MIN_LIMIT = 1
AUTOCOMPLETE_MAX_LIMIT = 10

APPLICABILITY_DEFAULT_LIMIT = 10
APPLICABILITY_MIN_LIMIT = 1
APPLICABILITY_MAX_LIMIT = 50

# Rate limiter
TECDOC_WINDOW_SECONDS = 3600

# TecDoc API
TECDOC_REQUEST_TIMEOUT = 30.0

# DB pool
DB_POOL_SIZE = 20
DB_MAX_OVERFLOW = 10

# Auth
PASSWORD_RESET_EXPIRY_HOURS = 1
RESET_TOKEN_BYTES = 32
PASSWORD_MIN_LENGTH = 6

# Sync
DEFAULT_VEHICLE_GROUP = "passenger"

# Storage keys
STORAGE_KEY_TOKEN = "token"
STORAGE_KEY_LAST_ORDER_CHECK = "lastOrderCheck"
